"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let BO=2463534242,B9=()=>{let x=BO;x^=x<<13;x^=x>>>17;x^=x<<5;BO=x;return x;},F=f=>function(){return f(this);},G=f=>function(p1){return f(this,p1);},N=f=>function(p1,p2){return f(this,p1,p2);},CT=f=>function(p1,p2,p3){return f(this,
p1,p2,p3,p3);},Cf=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=Bm(L(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=O(args[i]);}Cq(()=>{f.call(null,javaArgs);},callback);},U=target=>target.$clinit=()=>{},Cz=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E
=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=L();}return function(){superclass.call(this);};},Bw=cls=>Ce(cls),L=()=>D,CE=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},BT=(name,binaryName)=>{let cls=CE();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Bx=BT("char",
"C"),CS=BT("int","I");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let Cb=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;};
function C8(lo,hi){this.lo=lo|0;this.hi=hi|0;}
if(typeof BigInt!=="function"){}else {}if(typeof BigInt!=='function'){function Dd(lo,hi,sup){this.lo=lo;this.hi=hi;this.sup=sup;}
}else {}let Bm=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Be(cls))(data);};
if(typeof BigInt64Array!=='function'){}else {}let V=sz=>new Cv(new Uint16Array(sz)),Be=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(L()).call(this);this.data=data;}JavaArray.prototype=Object.create((L()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.M=function(){let dataCopy;if
('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Be(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[L()],primitive:false,superclass:L(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},Bf,Cn
=strings=>{C3();Bf=new Array(strings.length);for(let i=0;i<strings.length;++i){Bf[i]=BE(O(strings[i]));}},W=index=>Bf[index],BC=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},O=str=>str===null?null:CX(str),BX=str=>str===null?null:str.F,C3=()=>M(),BE;
{BE=str=>str;}let Bd=ex=>{throw C4(ex);},Y=Symbol("javaException"),C4=ex=>{let err=ex.$jsException;if(!err){let javaCause=C0(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new I("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Y]=ex;ex.$jsException=err;C2(err,ex);}return err;},C2=(err,ex)=>{if(typeof CP==="function"&&err.stack){let stack=CP(err.stack);let javaStack=Bm(Cg(),
stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Ct(O(element.className),O(element.methodName),O(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){CQ(ex,javaStack);}}},I;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");I=function I(message,cause){let self=Reflect.construct(Error,[void 0,cause],I);Object.setPrototypeOf(self,I.prototype);self[defaultMessage]=message;return self;}
;I.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:I},message:{get(){try {let javaException=this[Y];if(typeof javaException==='object'){let javaMessage=B5(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {I=Error;}let Cj=e=>e instanceof Error&&typeof e[Y]==='object'?e[Y]:null,B5=t=>BW(t),C0
=t=>B0(t),Cg=()=>Dg,Ct=(className,methodName,fileName,lineNumber)=>{{return null;}},CQ=(e,stack)=>{},BV=null,B6=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}BV=packages;},CY=data=>{let packages=BV;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex
=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo
===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func
=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},Cq=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function D(){this.$id$=0;}
let J=a=>{return;},Df=()=>{let a=new D();J(a);return a;},BR=a=>{let b,c;b=Ck(BZ(a));c=Cl();Bk(Bk(c,W(0)),b);return BD(c);},BZ=a=>{let b;b=a;if(!b.$id$)b.$id$=B9();return a.$id$;};
function P(){let a=this;D.call(a);a.K=null;a.J=null;a.I=0;a.H=0;}
let Bv=a=>{a.I=1;a.H=1;a.f();},C7=()=>{let a=new P();Bv(a);return a;},BL=(a,b)=>{a.I=1;a.H=1;a.f();a.K=b;},De=a=>{let b=new P();BL(b,a);return b;},CK=a=>{return a;},BW=a=>{return a.K;},B0=a=>{return a.J===a?null:a.J;},R=E(P),Bn=a=>{Bv(a);},C$=()=>{let a=new R();Bn(a);return a;},Bb=(a,b)=>{BL(a,b);},C_=a=>{let b=new R();Bb(b,a);return b;},K=E(R),Bc=a=>{Bn(a);},Da=()=>{let a=new K();Bc(a);return a;},BI=(a,b)=>{Bb(a,b);},C9=a=>{let b=new K();BI(b,a);return b;},X=E(K),Bp=a=>{Bc(a);},Cr=()=>{let a=new X();Bp(a);return a;},C5
=E(),Cs=(b,c)=>{let d,e,f,g;d=b.data;e=V(c);f=CJ(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},C1=E(K),S=E(0),Bj=E(),T=E(0),BF=E(Bj),Cp=null,Z=()=>{Z=U(BF);B7();},Ck=b=>{Z();return Cc(b,4);},CI=b=>{let c,d,e;Z();if(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;e=d>>>8|0;if(!e)e=d;else c=c|8;d=e>>>4|0;if(!d)d=e;else c=c|4;e=d>>>2|0;if(!e)e=d;else c=c|2;if(e>>>1|0)c=c|1;return (32-c|0)-1|0;},B7=()=>{Cp=Bw(CS);},CB=E(),Bl=E(),Co=null,CL=null,Bh=()=>{Bh=U(Bl);CU();},CM=(b,c)=>{Bh();if(c>=2&&c<=
36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},CU=()=>{Co=Bw(Bx);CL=Bm(Bl,128);},CR=E(),Cc=(b,c)=>{let d,e,f,g,h,i,j,k;if(!b)return W(1);d=1<<c;e=d-1|0;f=(((32-CI(b)|0)+c|0)-1|0)/c|0;g=V(f);h=Cb(f-1|0,c);i=0;while(h>=0){j=g.data;k=i+1|0;j[i]=CM((b>>>h|0)&e,d);h=h-c|0;i=k;}return CG(g);},Ba=E(0);
function Q(){let a=this;D.call(a);a.E=null;a.G=0;}
let Bo=a=>{Bg(a,16);},Dc=()=>{let a=new Q();Bo(a);return a;},Bg=(a,b)=>{J(a);a.E=V(b);},Db=a=>{let b=new Q();Bg(b,a);return b;},Bt=(a,b)=>{return a.n(a.G,b);},Bz=(a,b,c)=>{let d,e,f;if(b>=0&&b<=a.G){if(c===null)c=W(2);else if(c.o())return a;a.p(a.G+c.q()|0);d=a.G-1|0;while(d>=b){a.E.data[d+c.q()|0]=a.E.data[d];d=d+(-1)|0;}a.G=a.G+c.q()|0;d=0;while(d<c.q()){e=a.E.data;f=b+1|0;e[b]=c.r(d);d=d+1|0;b=f;}return a;}Bd(BH());},BG=(a,b,c)=>{return a.s(b,c===null?W(2):c.e());},BJ=(a,b)=>{let c;if(a.E.data.length>=b)return;c
=a.E.data.length>=1073741823?2147483647:By(b,By(a.E.data.length*2|0,5));a.E=Cs(a.E,c);},B1=a=>{return B$(a.E,0,a.G);},CN=E(),CJ=(b,c)=>{if(b<c)c=b;return c;},By=(b,c)=>{if(b>c)c=b;return c;},H=E(),Ci=null,Cw=null,Ca=null,M=()=>{M=U(H);Ch();},BN=a=>{M();J(a);a.F="";},CH=()=>{let a=new H();BN(a);return a;},BB=(a,b)=>{let c;M();c=b.data;J(a);a.F=BC(b.data,0,c.length);},CG=a=>{let b=new H();BB(b,a);return b;},Bs=(a,b)=>{a.F=b;},CX=a=>{let b=new H();Bs(b,a);return b;},BY=(a,b,c,d)=>{let e;M();e=b.data;J(a);CZ(c,
d,e.length);a.F=BC(b.data,c,d);},B$=(a,b,c)=>{let d=new H();BY(d,a,b,c);return d;},CO=(a,b)=>{if(b>=0&&b<a.F.length)return a.F.charCodeAt(b);Bd(BH());},CA=a=>{return a.F.length;},B4=a=>{return a.F.length?0:1;},CC=a=>{return a;},Ch=()=>{Ci=V(0);Cw=CH();Ca=CF();},C6=E(),B2=E(0),BM=E(X),B3=a=>{Bp(a);},BH=()=>{let a=new BM();B3(a);return a;},Cd=E(),CZ=(b,c,d)=>{if(b>=0&&c>=0&&c<=(d-b|0))return b;Bd(Cr());},BS=E(0),BA=E(),Bi=()=>{Bi=U(BA);Cm();},CV=b=>{Bi();},Cm=()=>{return;},Bq=E(0);
function BP(){D.call(this);this.L=null;}
let CD=(a,b)=>{let c;J(a);a.L=b;c=a;b.classObject=c;},B_=a=>{let b=new BP();CD(b,a);return b;},Ce=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null)c=B_(b);return c;},Br=E(Q),BQ=a=>{Bo(a);},Cl=()=>{let a=new Br();BQ(a);return a;},Bk=(a,b)=>{Bt(a,b);return a;},Cu=(a,b,c)=>{BG(a,b,c);return a;},CW=(a,b,c)=>{Bz(a,b,c);return a;},BD=a=>{return B1(a);},B8=(a,b)=>{BJ(a,b);},Cx=(a,b,c)=>{return a.z(b,c);},Cy=(a,b,c)=>{return a.A(b,c);},BK=E(0),Bu=E(),BU=a=>{J(a);},CF=()=>{let a=new Bu();BU(a);return a;};
B6([]);
CY([D,0,0,[],0,3,0,0,["e",F(BR),"b",F(BZ)],P,0,D,[],0,3,0,0,["f",F(CK),"B",F(BW),"C",F(B0)],R,0,P,[],0,3,0,0,["c",F(Bn),"g",G(Bb)],K,0,R,[],0,3,0,0,["c",F(Bc),"g",G(BI)],X,0,K,[],0,3,0,0,["c",F(Bp)],C5,0,D,[],0,3,0,0,0,C1,0,K,[],0,3,0,0,0,S,0,D,[],3,3,0,0,0,Bj,0,D,[S],1,3,0,0,0,T,0,D,[],3,3,0,0,0,BF,0,Bj,[T],0,3,0,Z,0,CB,0,D,[],4,3,0,0,0,Bl,0,D,[T],0,3,0,Bh,0,CR,0,D,[],4,3,0,0,0,Ba,0,D,[],3,3,0,0,0,Q,0,D,[S,Ba],0,0,0,0,["c",F(Bo),"m",G(Bg),"y",G(Bt),"s",N(Bz),"n",N(BG),"p",G(BJ),"e",F(B1)],CN,0,D,[],4,3,0,0,
0,H,0,D,[S,T,Ba],0,3,0,M,["c",F(BN),"l",G(BB),"D",G(Bs),"v",CT(BY),"r",G(CO),"q",F(CA),"o",F(B4),"e",F(CC)],C6,0,D,[],4,0,0,0,0,B2,0,D,[],3,3,0,0,0,BM,0,X,[],0,3,0,0,["c",F(B3)],Cd,0,D,[],4,3,0,0,0,BS,0,D,[],3,3,0,0,0,BA,0,D,[],0,3,0,Bi,0,Bq,0,D,[],3,3,0,0,0,BP,0,D,[Bq,BS],0,3,0,0,0,Br,0,Q,[B2],0,3,0,0,["c",F(BQ),"d",G(Bk),"z",N(Cu),"A",N(CW),"e",F(BD),"p",G(B8),"n",N(Cx),"s",N(Cy)],BK,0,D,[],3,3,0,0,0,Bu,0,D,[BK],0,3,0,0,["c",F(BU)]]);
let Cv=Be(Bx);
Cn(["<java_object>@","0","null"]);
H.prototype.toString=function(){return BX(this);};
H.prototype.valueOf=H.prototype.toString;D.prototype.toString=function(){return BX(BR(this));};
D.prototype.__teavm_class__=function(){return Cz(this);};
let C=Cf(CV);
C.javaException=Cj;
B.main=C;}));
